//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.05 at 11:30:49 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.vdab.be/koersen")
package be.vdab.entities;
